[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "gcc", "postgresql"]

[phases.install]
cmds = ["python3 -m venv /opt/venv", "/opt/venv/bin/pip install -r backend/requirements.txt"]

[start]
cmd = "PATH=\"/opt/venv/bin:$PATH\" cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
